### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by Stam21** [Stam21/Algoland#8]
* Decide which framework to use for rendering the page into the server, thus improving performance
* Popular options -> Next.js / Gatsby

**Comment by GeorgeMoucht** [comment]
I was looking [this](https://www.youtube.com/watch?v=c8_kEVCcQvg&ab_channel=AlterClass) video. It is about pros and cons of this two frameworks.

In my opinion, Next.js is way better that Gatsby because it is possible to render data from anything. Rest API, Database, CMS.
Plus on Next.js it is possible to do any calls you want from node.js (sync, async etc.) .

The problem here is that as I saw if we want to use any of this frameworks for back-end rendering, we must not start react project with `npm create-app-react`. So probably we need to recreate the core of frontend directory.

**Comment by GeorgeMoucht** [comment]
On the 8-serverr-side-rendering branch, I have already re-installed next.js. To get this done, I need to re-write the basic components and routing we have and then merge it with main.

**Comment by Stam21** [comment]
we proceed with next.js
